### ISSUE TITLE
Unknown element: <vue-toastr>

### ISSUE THREAD

**Issue by LuizLeite** [chengxulvtu/cxlt-vue2-toastr#12]
Hi.

In cxlt-vue2-toastr" version 1.0.12

ERROR: "Unknown custom element: \<vue-toastr\> - did you register the component correctly?"

This error after apperars when i run the app.

I install this by npm process with css at html file with style tag.

What is this error reffer?

Tanks

**Comment by chengxulvtu** [comment]
@LuizLeite  `this.$toast.success({
    title:'',
    message:''
})`

 Use this way
