### ISSUE TITLE
Documentation is not in sync with the latest from NPM

### ISSUE THREAD

**Issue by miguellara78** [chengxulvtu/cxlt-vue2-toastr#2]
If you install the latest from npm (1.0.6 at the moment), and try to use the plug in as stated with the current documentation you will receive an error: 

**_[Vue warn]: Unknown custom element: <cxlt-toastr> - did you register the component correctly? For recursive components, make sure to provide the "name" option_**.

Looks like the <cxlt-toastr ></cxlt-toastr> tag is not longer valid and it has to be omitted, and now you call and show the toaster from the Vue instance as:

this.$toast.success({title:'Test',message:'This is just a test'})

After doing that toaster shows up. I am not sure if that is the only change or if there are also other changes in the toaster object.

Besides that it works great, nice job.

**Comment by chengxulvtu** [comment]
@miguellara78  Already sync. Thanks

**Comment by miguellara78** [comment]
Great thank you.
Have you thought about listing your plug-in in the Awesome-Vue repository? Honestly I think that your 
 Vue implementation of toaster is the best i've seen, really robust and functional,  but it was hard to find. If you list it there you will be getting a lot more traffic.
This is the link in case you are interested.

https://github.com/vuejs/awesome-vue

Thank you.

**Comment by chengxulvtu** [comment]
@miguellara78  Thanks for your appreciation,I'll try.
