### ISSUE TITLE
License as Free Software?

### ISSUE THREAD

**Issue by bernhardreiter** [chengxulvtu/cxlt-vue2-toastr#25]
Dear @chengxulvtu,

what what conditions can cxlt-vue2-toastr be used?

Looking at the source code and in the repo I could not find a statement about this. It would be nice to know. If you want people just to use your software, why not put it under a Free Software license ("some say open source"). See https://producingoss.com/en/license-quickstart.html for a starting guide, you may also consider the Apache-2.0 license.

Best Regards,
Bernhard

**Comment by chengxulvtu** [comment]
@bernhardreiter 
MIT license

**Comment by bernhardreiter** [comment]
@chengxulvtu thanks for clarifying that vue2-toastr is Free Software!

Best would be to commit this into the repo itself, so more people can find this information.
At least in the license SPDX identifies in package.json.

```json
"license": "MIT",
```

and add the license file as seen here https://spdx.org/licenses/MIT.html#licenseText
