### ISSUE TITLE
Toast instances are not destroyed.

### ISSUE THREAD

**Issue by NJM8** [chengxulvtu/cxlt-vue2-toastr#27]
Hello, thank you for the great package, really easy to setup and use. 

I have noticed that toast instances do not get destroyed and I end up with many instances in my application. Is there a way to destroy them so that they do not cause a memory leak over time?

I am using Firefox dev edition on Windows 10 and Vue 2.6.8.

![image](https://user-images.githubusercontent.com/12437197/54753496-8db41b00-4bb7-11e9-9633-32538a2e8a94.png)

**Comment by chengxulvtu** [comment]
I uses <b>v-if</b> directive , so there will be no such thing as what you said.
