### ISSUE TITLE
Animations have a jerky behavior on the opacity transitions.

### ISSUE THREAD

**Issue by miguellara78** [chengxulvtu/cxlt-vue2-toastr#3]
I am not sure if this is the way it was designed or it is the intended behavior, but when there is a transition fro opacity 0 to opacity 100%, at the end of the animation the opacity goes down a little to 80% opacity in a split second and it stays that way until times out, then it goes back to 100% opacity again in a split second and it starts to fade out normally.

To me it looks kind of jerky so what I did, is I modified the transitions in the .css file so they all go from 0 to .9 and stay there and then go back from .9 to 0, so they never reach 100% opacity, I think it looks much more smoother that [way.]

So again I am not sure if this is an issue or not, I just thought it looks a little jerky.

I attached a .zipped  modified .css in case you want to see the difference.

[cxlt-vue2-toastr.zip](https://github.com/chengxulvtu/cxlt-vue2-toastr/files/1031234/cxlt-vue2-toastr.zip)

If that is the intended behavior then just close this issue and I'll just keep a copy of my modified .css for reference.

Thank you.

**Comment by chengxulvtu** [comment]
@miguellara78  It disappears when show duration greater than or equal to time out . But I'll think about your advice.

**Comment by chengxulvtu** [comment]
I have already fix this bug. Please see the example.

**Comment by chengxulvtu** [comment]
@miguellara78  I have already fix this bug. Please see the example.

**Comment by miguellara78** [comment]
That looks so much better now. 
Thank you for looking at it, I am including your library on a project I am working on for work if you don't mind.
