### ISSUE TITLE
Chinese documentation makes it really hard to read :-(

### ISSUE THREAD

**Issue by kuceram** [chengxulvtu/cxlt-vue2-toastr#5]

**Comment by chengxulvtu** [comment]
@kuceram  Can you give me a hand with writing an english doc.

**Comment by miguellara78** [comment]
I can help you with that, I do a lot of our documentation of our software at work, so I do have some experience with it. I could also translate to Spanish in case you want to include that as well.

**Comment by chengxulvtu** [comment]
@miguellara78  Thanks. You can fork the project and then pull request.

**Comment by kuceram** [comment]
@miguellara78 hey, thank you too. Haven't found time for this yet. Mark me in pull request and I can do the review. :-P

**Comment by chengxulvtu** [comment]
@realdah  Ok, thanks
